# Generated by Django 2.2.1 on 2019-05-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(max_length=70)),
                ('contactnumber', models.CharField(max_length=10, unique=True)),
                ('username', models.ForeignKey(on_delete='CASCADE', related_name='usernames', to='backup.Username')),
            ],
        ),
    ]
