# Generated by Django 2.2.1 on 2019-05-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contactnumber',
            field=models.CharField(max_length=10),
        ),
    ]
